Update plugin author, URI, item ID
easydigitaldownloads/edd-widgets-pack pull request #17
Opened 2021-04-09 13:27 UTC by robincornett

Fixes #15

2021-04-12 17:40 UTC, LisaCee requested changes

2021-04-12 17:40 UTC, LisaCee commented on edd-widgets-pack.php
> + * Plugin URL: https://easydigitaldownloads.com/downloads/widgets-bundle/
Will you change this to URI so that it has a link from the Plugin page?

2021-04-12 20:07 UTC, LisaCee approved these changes

2021-05-24 12:13 UTC, ashleyfae approved these changes

2021-05-24 12:13 UTC, merged