# 16 PHP Notices and Formatting
easydigitaldownloads/edd-widgets-pack pull request #18
Opened 2021-04-12 23:32 UTC by LisaCee

Fixes #16 
- Adds check for undefined index in Archives, formatting

2021-04-16 14:51 UTC, ashleyfae commented on widgets/edd-widget-archives.php
> +				// get the title and apply .
Was the word `filters` removed accidentally?

2021-04-16 14:53 UTC, ashleyfae commented on widgets/edd-widget-archives.php
> +			$instance['show_count'] = '1' === $instance['show_count'] ? 1 : 0;
I think we can simplify the above two lines into just one like this:

```php
$instance['show_count'] = ! empty( $new_instance['show_count'] ) && '1' === $new_instance['show_count'] ? 1 : 0;
```

There's no need to do all the tag stripping stuff if we're checking if it's equal to `'1'` anyway.

2021-04-16 14:58 UTC, ashleyfae commented on widgets/edd-widget-downloads-calendar.php
> +				if ( $day == gmdate( 'j', current_time( 'timestamp' ) ) && gmdate( 'm', current_time( 'timestamp' ) ) === $thismonth && gmdate( 'Y', current_time( 'timestamp' ) ) === $thisyear ) {
I think we actually want the old condition ordering, with variables first.

2021-04-16 15:00 UTC, ashleyfae commented on widgets/edd-widget-featured-download.php
> +						// append the downloads title.
I think `download's` is correct, as it's referring to the title of the download.

2021-04-16 15:01 UTC, ashleyfae commented on widgets/edd-widget-featured-download.php
> +			$instance['show_price'] = '1' === $instance['show_price'] ? 1 : 0;
The same simplification I recommended in the other widget (one liner) can be applied here.

2021-04-16 15:01 UTC, ashleyfae commented on widgets/edd-widget-featured-download.php
> +			$instance['thumbnail'] = '1' === $instance['thumbnail'] ? 1 : 0;
The same simplification I recommended in the other widget (one liner) can be applied here.

2021-04-16 15:02 UTC, ashleyfae commented on widgets/edd-widget-most-commented.php
> +			$instance['show_price'] = '1' === $instance['show_price'] ? 1 : 0;
The same simplification I recommended in the other widget (one liner) can be applied here.

2021-04-16 15:02 UTC, ashleyfae commented on widgets/edd-widget-most-commented.php
> +			$instance['thumbnail'] = '1' === $instance['thumbnail'] ? 1 : 0;
The same simplification I recommended in the other widget (one liner) can be applied here.

2021-04-16 15:03 UTC, ashleyfae commented on widgets/edd-widget-downloads-calendar.php
> +				if ( $day == gmdate( 'j', current_time( 'timestamp' ) ) && gmdate( 'm', current_time( 'timestamp' ) ) === $thismonth && gmdate( 'Y', current_time( 'timestamp' ) ) === $thisyear ) {
Actually I'm backwards. What we want to change is the _first_ one to match the others.

2021-04-16 15:04 UTC, ashleyfae commented on widgets/edd-widget-most-recent.php
> +			$instance['show_price'] = '1' === $instance['show_price'] ? 1 : 0;
The same simplification I recommended in the other widget (one liner) can be applied here.

2021-04-16 15:04 UTC, ashleyfae commented on widgets/edd-widget-most-recent.php
> +			$instance['thumbnail'] = '1' === $instance['thumbnail'] ? 1 : 0;
The same simplification I recommended in the other widget (one liner) can be applied here.

2021-04-16 15:05 UTC, ashleyfae commented on widgets/edd-widget-random-download.php
> +			// set the widgets containers.
I think `widget's` is correct here.

2021-04-16 15:05 UTC, ashleyfae commented on widgets/edd-widget-random-download.php
> +			$instance['show_price'] = '1' === $instance['show_price'] ? 1 : 0;
The same simplification I recommended in the other widget (one liner) can be applied here.

2021-04-16 15:05 UTC, ashleyfae commented on widgets/edd-widget-random-download.php
> +			$instance['thumbnail'] = '1' === $instance['thumbnail'] ? 1 : 0;
The same simplification I recommended in the other widget (one liner) can be applied here.

2021-04-16 15:09 UTC, ashleyfae requested changes
Awesome start so far! This plugin looks really nasty so I applaud you for tackling it. :D

2021-04-16 15:09 UTC, ashleyfae commented on widgets/edd-widget-related-downloads.php
> +			while ( $product_number < $limit && isset( $terms_in[ $c ] ) ) {
The `count()` actually needs to be moved back inline. Pretty sure it won't work with it put in a variable like this.

2021-04-16 15:09 UTC, ashleyfae commented on widgets/edd-widget-related-downloads.php
> +			$instance['show_price'] = '1' === $instance['show_price'] ? 1 : 0;
Let's one-liner this.

2021-04-16 15:09 UTC, ashleyfae commented on widgets/edd-widget-related-downloads.php
> +			$instance['thumbnail'] = '1' === $instance['thumbnail'] ? 1 : 0;
Let's one-liner this.

2021-04-16 16:31 UTC, LisaCee commented on widgets/edd-widget-related-downloads.php
> +			while ( $product_number < $limit && isset( $terms_in[ $c ] ) ) {
The linter didn't like the original, but I defer to your expertise.  

`The use of count() inside a loop condition is not allowed; assign the return value to a variable and use the variable in the loop condition instead phpcs`

2021-04-19 17:38 UTC, robincornett reviewed
This is a huge improvement already!

2021-04-19 17:38 UTC, robincornett commented on widgets/edd-widget-downloads-calendar.php
> +				if ( 6 === calendar_week_mod( date( 'w', mktime( 0, 0, 0, $thismonth, $day, $thisyear ) ) - $week_begins ) ) {
It appears that this is failing--doing some dumping shows that the code is returning `6` as a float and it's being compared to an integer, so the strict comparison fails and the calendar output is just one long row.

I think I would also move the PHP evaluation outside of the conditional for safety, and I think it's just more readable. I'm comparing the code and it almost seems like you could extract a significant amount to be assigned to a variable and then used for the computation in line 326, instead of duplicating the code. (That's personal preference on my part)

2021-04-19 17:38 UTC, robincornett commented on widgets/edd-widget-downloads-calendar.php
> +			if ( 0 !== $pad && 7 !== $pad ) {
The strict comparison may also be problematic here, as I'm guessing that `$pad` is a float value. I don't know if it would be better to keep it as a loose comparison or to cast `$pad` to an integer--the latter would be my preference, I think. Same for the bit in line 321.

2021-04-19 17:38 UTC, robincornett commented on widgets/edd-widget-featured-download.php
> +			if ( false == $cache = get_transient( 'edd_widgets_featured_download_' . $this->id ) ) {
I would vote for moving the variable assignment out of the conditional here as well.

2021-04-19 17:38 UTC, robincornett commented on widgets/edd-widget-most-commented.php
> +						if ( $show_price === 1 ) {
This logic could be yoda'ed as well.

2021-04-19 17:38 UTC, robincornett commented on widgets/edd-widget-most-recent.php
> +			// contruct widget.
```suggestion
			// construct widget.
```

2021-04-19 17:38 UTC, robincornett commented on widgets/edd-widget-most-recent.php
> +					if ( 1 === $thumbnail && function_exists( 'has_post_thumbnail' ) && has_post_thumbnail( $download->ID ) ) {
I didn't check this in the other widgets, but apparently `has_post_thumbnail` was introduced in WP 2.9. I feel like we could remove the `function_exists` check.

2021-04-19 17:38 UTC, robincornett commented on widgets/edd-widget-related-downloads.php
> +			$instance['limit'] = ( (bool) preg_match( '/^\-?[0-9]+$/', $instance['limit'] ) ) && $instance['limit'] > -2 ? $instance['limit'] : 4;
I'm trying to figure out why the `preg_match` is necessary and I'm thinking it's because this input is a text input, instead of a number. It might be good to go ahead and make it a number input, with a `min` of `-1` as that appears to be an allowed value. I think there are other similar inputs as well.

2021-04-23 00:05 UTC, LisaCee commented on widgets/edd-widget-archives.php
> +		function form( $instance ) {
I _think_ I've done this, but escaping is still rough so please double check me.  Also, WAVE is marking the checkbox as not having a label and I'm not sure how to remedy that.

2021-04-25 20:28 UTC, LisaCee commented on widgets/edd-widget-most-recent.php
> +					if ( 1 === $thumbnail && function_exists( 'has_post_thumbnail' ) && has_post_thumbnail( $download->ID ) ) {
Nice catch.  I removed the check from all of the widgets.

2021-04-25 21:36 UTC, LisaCee commented on widgets/edd-widget-related-downloads.php
> +			$instance['limit'] = ( (bool) preg_match( '/^\-?[0-9]+$/', $instance['limit'] ) ) && $instance['limit'] > -2 ? $instance['limit'] : 4;
I changed the quantities and thumbnail size inputs to be numbers and added minimum values.  The thumbnail fields are `class="widefat"` where the others were `class="small"` which doesn't seem to be used anymore.  Do you think all of the number inputs should be the same size and if so, default or widefat?

2021-04-27 00:57 UTC, LisaCee commented on widgets/edd-widget-downloads-calendar.php
> +				if ( 6 === calendar_week_mod( date( 'w', mktime( 0, 0, 0, $thismonth, $day, $thisyear ) ) - $week_begins ) ) {
I think this is working now, though I'm still working on moving the evaluation outside of the conditional.

2021-04-27 14:59 UTC, robincornett commented on widgets/edd-widget-featured-download.php
> +			$cache = get_transient( 'edd_widgets_featured_download_' . $this->id );
You know what's interesting about this? It will always be `false` and I don't think ever would have worked. This line checks for a specific widget instance transient, but the transient that is set at the end is not specific to the instance; it's just `edd_widgets_featured_download`.

I think lines 139 and 186 need to be updated to use this transient name--but there is so much fixing going on in this PR that maybe it's worth doing that as just its own smaller issue.

2021-04-27 14:59 UTC, robincornett commented on widgets/edd-widget-most-commented.php
> +					<input type="number" min="-1" size="3" id="<?php echo $this->get_field_id( 'limit' ); ?>" name="<?php echo $this->get_field_name( 'limit' ); ?>" type="text" value="<?php echo $limit; ?>"/>
I think this would be a good opportunity to go ahead and escape all of the input attributes and values when they're being echoed in this widget.

I would also remove the `size` attribute from this and add a `small-text` class instead.

2021-04-27 14:59 UTC, robincornett commented on widgets/edd-widget-most-recent.php
> +				<input type="number" min="0" size="3" id="<?php echo $this->get_field_id( 'offset' ); ?>" name="<?php echo $this->get_field_name( 'offset' ); ?>" type="text" value="<?php echo $offset; ?>"/>
Same as with the previous widget--I vote go ahead and remove `size` and then escape everything.

2021-04-27 14:59 UTC, robincornett commented on widgets/edd-widget-random-download.php
> +					<input type="number" min="0" class="widefat" id="<?php echo $this->get_field_id( 'thumbnail_size' ); ?>" name="<?php echo $this->get_field_name( 'thumbnail_size' ); ?>" type="text" value="<?php
More escaping opportunities here please.

2021-04-27 14:59 UTC, robincornett commented on widgets/edd-widget-related-downloads.php
> +			while ( count( $related_downloads ) < $limit && isset( $terms_in[ $c ] ) ) {
I know this isn't yours, but PHPCS is not happy about this use of `count`, so let's fix it:

> The use of count() inside a loop condition is not allowed; assign the return value to a variable and use the variable in the loop condition instead.

Wondering if the `isset` check should be first as well--that feels more typical to me.

2021-04-27 14:59 UTC, robincornett commented on widgets/edd-widget-related-downloads.php
> +							if ( count( $related_downloads ) === $limit ) {
Once the `count` is assigned to a variable, it can be reused here.

2021-04-27 14:59 UTC, robincornett commented on widgets/edd-widget-related-downloads.php
> +					++$c;
This is totally working but I've always seen it as `$c++` ...just wondering if one way is more typical or preferred over the other?

2021-04-27 14:59 UTC, robincornett commented on widgets/edd-widget-related-downloads.php
> +					<input type="number" min="-1" size="3" id="<?php echo $this->get_field_id( 'limit' ); ?>" name="<?php echo $this->get_field_name( 'limit' ); ?>" type="text" value="<?php echo $limit; ?>"/>
Escaping please :)

2021-04-27 14:59 UTC, robincornett commented on widgets/edd-widget-top-sellers.php
> +					<input type="number" min="-1" size="3" id="<?php echo $this->get_field_id( 'limit' ); ?>" name="<?php echo $this->get_field_name( 'limit' ); ?>" type="text" value="<?php echo $limit; ?>"/>
`size` and escaping all the things please.

2021-04-28 18:00 UTC, LisaCee commented on widgets/edd-widget-featured-download.php
> +			$cache = get_transient( 'edd_widgets_featured_download_' . $this->id );
I created a new issue here: #20

2021-04-28 20:12 UTC, LisaCee commented on widgets/edd-widget-related-downloads.php
> +					++$c;
I'm going to change it to the more typical format.  It shouldn't really matter here, but `$++a` increments `$a` by one and then returns `$a` while `$a++` returns first and then increments.

2021-04-28 20:31 UTC, LisaCee commented on widgets/edd-widget-downloads-calendar.php
> +				if ( 6 === calendar_week_mod( date( 'w', mktime( 0, 0, 0, $thismonth, $day, $thisyear ) ) - $week_begins ) ) {
I moved the computation to its own variable and cast it as an int.  I wasn't able to assign it to a variable, though, because this instance is dependent on the for loop whereas line 326 (now 331) is outside of the loop.

2021-04-29 20:19 UTC, robincornett requested changes

2021-04-29 20:19 UTC, robincornett commented on widgets/edd-widget-top-sellers.php
> +					<label for="<?php echo esc_attr( $this->get_field_id( 'title' ) ); ?>"><?php esc_attr__( 'Title:', 'edd-widgets-pack' ); ?></label>
Same for the labels here please.

2021-05-03 18:11 UTC, robincornett approved these changes

2021-05-07 14:51 UTC, ashleyfae commented on widgets/edd-widget-most-commented.php
> -            $instance['limit'] = ( ( bool ) preg_match( '/^\-?[0-9]+$/', $instance['limit'] ) ) && $instance['limit'] > -2 ? $instance['limit'] : 4;
Seems like it could be beneficial to keep this preg_match() logic.

2021-05-07 14:52 UTC, ashleyfae commented on widgets/edd-widget-most-commented.php
> -            $instance['thumbnail_size'] = ( ( bool ) preg_match( '/^[0-9]+$/', $instance['thumbnail_size'] ) ) ? $instance['thumbnail_size'] : 80;
Let's keep the preg_match.

2021-05-07 15:01 UTC, ashleyfae requested changes

2021-05-07 15:01 UTC, ashleyfae commented on widgets/edd-widget-related-downloads.php
> +					<input type="number" min="-1" class="small-text" id="<?php echo esc_attr( $this->get_field_id( 'limit' ) ); ?>" name="<?php echo esc_attr( $this->get_field_name( 'limit' ) ); ?>" type="text" val
This has both `type="number"` and `type="text"`

2021-05-07 15:01 UTC, ashleyfae commented on widgets/edd-widget-top-sellers.php
> -            $instance['limit'] = ( ( bool ) preg_match( '/^\-?[0-9]+$/', $instance['limit'] ) ) && $instance['limit'] > -2 ? $instance['limit'] : 4;
Let's keep the `preg_match()`

2021-05-07 15:01 UTC, ashleyfae commented on widgets/edd-widget-top-sellers.php
> -            $instance['thumbnail_size'] = ( ( bool ) preg_match( '/^[0-9]+$/', $instance['thumbnail_size'] ) ) ? $instance['thumbnail_size'] : 80;
Let's keep the `preg_match()`

2021-05-07 15:01 UTC, ashleyfae commented on widgets/edd-widget-top-sellers.php
> +					<input type="number" min="-1" class="small-text" id="<?php echo esc_attr( $this->get_field_id( 'limit' ) ); ?>" name="<?php echo esc_attr( $this->get_field_name( 'limit' ) ); ?>" type="text" val
This has both `type="number"` and `type="text"`

2021-05-07 15:01 UTC, ashleyfae commented on widgets/edd-widget-top-sellers.php
> +					<input type="number" min="0" class="widefat" id="<?php echo esc_attr( $this->get_field_id( 'thumbnail_size' ) ); ?>" name="<?php echo esc_attr( $this->get_field_name( 'thumbnail_size' ) ); ?>" t
This has both `type="number"` and `type="text"`

2021-05-10 12:41 UTC, robincornett commented on widgets/edd-widget-featured-download.php
> +			$instance['thumbnail_size'] = ( (bool) preg_match( '/^[0-9]+$/', $new_instance['thumbnail_size'] ) );
This is no longer working--it looks like originally the `preg_match` was being cast to a boolean as the initial step in a ternary condition. Right now, it's just casting the thumbnail size to a `1` regardless of what number I put into the numeric input.

The original logic was:
```php
$instance['thumbnail_size'] = ( ( bool ) preg_match( '/^[0-9]+$/', $instance['thumbnail_size'] ) ) ? $instance['thumbnail_size'] : 80;
```

I suspect you will want to recheck all of the widgets with thumbnail image sizes in them; I only checked featured downloads.

2021-05-10 13:47 UTC, ashleyfae commented on widgets/edd-widget-featured-download.php
> +			$instance['thumbnail_size'] = ( (bool) preg_match( '/^[0-9]+$/', $new_instance['thumbnail_size'] ) );
Yeah really what we want I guess is something like:

```php
if ( ! empty( $new_instance['thumbnail_size'] ) && preg_match( '/^[0-9]+$/', $new_instance['thumbnail_size'] ) {
    $instance['thumbnail_size'] = $new_instance['thumbnail_size'];
} else {
    $instance['thumbnail_size'] = $some_default_number_here;
}
```

Or I would also be fine with:

```php
$instance['thumbnail_size'] = ! empty( $new_instance['thumbnail_size'] ) ? absint( $new_instance['thumbnail_size'] ) : $some_default_value_here;
```

Warning: Wrote that in the GitHub editor, don't trust there are no syntax errors. :P

2021-05-10 17:35 UTC, LisaCee commented on widgets/edd-widget-featured-download.php
> +			$instance['thumbnail_size'] = ( (bool) preg_match( '/^[0-9]+$/', $new_instance['thumbnail_size'] ) );
I opted for Ashley's second example.  Now that the input is a `number` field, I don't think that `preg_match` is needed, since only digits can be entered.  I did notice, though, that you can enter a negative value.  The `min` value will not allow a user to save a negative amount, but it also does not give any notices that it's an invalid value and has not saved.

2021-05-10 17:36 UTC, LisaCee commented on widgets/edd-widget-featured-download.php
> +			$instance['thumbnail_size'] = ( (bool) preg_match( '/^[0-9]+$/', $new_instance['thumbnail_size'] ) );
I opted for Ashley's second example.  Now that the input is a `number` field, I don't think that `preg_match` is needed, since only digits can be entered.  I did notice, though, that you can enter a negative value.  The `min` value will not allow a user to save a negative amount, but it also does not give any notices that it's an invalid value and has not saved.

2021-05-13 18:52 UTC, robincornett requested changes

2021-05-13 18:52 UTC, robincornett commented on widgets/edd-widget-most-commented.php
> +			$instance['limit'] = ( (bool) preg_match( '/^\-?[0-9]+$/', $instance['limit'] ) );
This is throwing a notice in the ajax--also it's casting it to a boolean. I think it needs to be something like this (typed in browser so don't trust me...also needs to end up allowing `-1` as a valid result):
```suggestion
			$instance['limit'] = ! empty( $instance['limit'] ) ? (int) $instance['limit'] : 4;
```

2021-05-13 18:52 UTC, robincornett commented on widgets/edd-widget-most-recent.php
> +			$instance['limit'] = ( (bool) preg_match( '/^\-?[0-9]+$/', $new_instance['limit'] ) );
This is going to have the same issue as the most commented widget limit, I think.

2021-05-13 18:52 UTC, robincornett commented on widgets/edd-widget-related-downloads.php
> +			$instance['limit'] = ( (bool) preg_match( '/^\-?[0-9]+$/', $new_instance['limit'] ) );
Same as the other limit fields--

2021-05-13 18:52 UTC, robincornett commented on widgets/edd-widget-top-sellers.php
> +			$instance['limit'] = ( (bool) preg_match( '/^\-?[0-9]+$/', $new_instance['limit'] ) );
This is being cast to a boolean as well (I know I'm being repetitive but not all of the widgets have a limit so I'm flagging them as I see them).

2021-05-19 19:58 UTC, LisaCee commented on widgets/edd-widget-most-commented.php
> +			$instance['limit'] = ( (bool) preg_match( '/^\-?[0-9]+$/', $instance['limit'] ) );
Your suggested code works for the ajax error.  I wonder why the min would be -1. I'd love to change it to 0 if you don't think there would be any larger implications, since -1 doesn't really make sense in this case.

2021-05-19 21:33 UTC, robincornett commented on widgets/edd-widget-most-commented.php
> +			$instance['limit'] = ( (bool) preg_match( '/^\-?[0-9]+$/', $instance['limit'] ) );
This field allows `-1` so that someone can tell the widget to display ALL the downloads (which seems counterintuitive based on the widget), but that is what was allowed. Interestingly, the empty check would fail if someone entered `0` in the field, which also seems counterintuitive, but do we need to allow `0` to be a value for it? If so, it should be an `isset` check, not an `empty` check.

2021-05-20 20:11 UTC, LisaCee commented on widgets/edd-widget-most-commented.php
> +			$instance['limit'] = ( (bool) preg_match( '/^\-?[0-9]+$/', $instance['limit'] ) );
I think you're right with changing it to `isset`.  `0` should evaluate to true for both, but it looks like `-1` is only true with `isset`.
Source: https://www.php.net/manual/en/types.comparisons.php

2021-05-21 12:56 UTC, robincornett requested changes

2021-05-21 12:56 UTC, robincornett commented on widgets/edd-widget-most-commented.php
> +			$instance['limit'] = isset( $instance['limit'] ) ? (int) $instance['limit'] : 4;
```suggestion
			$instance['limit'] = isset( $new_instance['limit'] ) ? (int) $new_instance['limit'] : 4;
```
Needs to check against the `$new_instance`.

2021-05-21 12:56 UTC, robincornett commented on widgets/edd-widget-related-downloads.php
> +			$instance['limit'] = isset( $instance['limit'] ) ? (int) $new_instance['limit'] : 4;
```suggestion
			$instance['limit'] = isset( $new_instance['limit'] ) ? (int) $new_instance['limit'] : 4;
```
Make sure you are checking the new instance--

2021-05-21 18:18 UTC, robincornett commented on widgets/edd-widget-most-commented.php
> +			$instance['limit'] = isset( $new_instance['limit'] ) ? (int) $instance['limit'] : 4;
```suggestion
			$instance['limit'] = isset( $new_instance['limit'] ) ? (int) $new_instance['limit'] : 4;
```
(both the check and the use need to be from the `$new_instance`)

2021-05-21 19:17 UTC, LisaCee commented on widgets/edd-widget-most-commented.php
> +			$instance['limit'] = isset( $new_instance['limit'] ) ? (int) $instance['limit'] : 4;
Sorry I missed that. I _think_ I've checked for every instance of `$instance['limit']` to make sure it's either the new variable name (like here) or used in a function where the incoming argument is `$instance`.

2021-05-24 10:45 UTC, robincornett approved these changes

2021-05-24 11:54 UTC, ashleyfae commented
## Tested

- [x] Archives
- [ ] Calendar
- [ ] Featured Download
- [ ] Most Commented
- [ ] Most Recent
- [ ] Random Download
- [ ] Related Downloads
- [ ] Top Sellers

2021-05-24 12:00 UTC, ashleyfae approved these changes
Nice work @LisaCee ! :raised_hands:

2021-05-24 12:01 UTC, merged